apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: xnl-fintech-dev

commonLabels:
  environment: development

patches:
  - path: replicas-patch.yaml

configMapGenerator:
  - name: env-config
    literals:
      - NODE_ENV=development

secretGenerator:
  - name: mongodb-secret
    literals:
      - uri=mongodb://mongodb:27017/xnl_dev
  - name: rabbitmq-secret
    literals:
      - url=amqp://guest:guest@rabbitmq:5672
  - name: jwt-secret
    literals:
      - secret=dev-jwt-secret-key
  - name: email-secret
    literals:
      - api-key=dev-email-api-key 